baseurl = "https://blog.biegala.net/"
languageCode = "pl-pl"
DefaultContentLanguage = "pl"
title = "Marcin Biegała o kodowaniu"
theme = "hugo-future-imperfect"
description = "Blog o kodowaniu, architekturze IT i społeczności"
preserveTaxonomyNames = true
paginate = 5
disqusShortname = "blogbiegalanet"
googleAnalytics = "UA-11867728-3"
metaDataFormat = "yaml"
enableRobotsTXT = true
canonifyURLs = true

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "Dev, motocyklista, marzyciel i miłośnik kawy."
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Marcin Biegała"
    # set this to the section name if section is not post
    viewMorePostLink     = "/blog/"

# Optional Params
    # Sets navbarTitle to match the section of the website
    dynamicTitles        = false
    # Sets RSS icons to appear on the sidebar with the social media buttons
    rssAppearAtTop       = true
    rssAppearAtBottom    = true
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # Sets Categories to sort by number of posts instead of alphabetical
    categoriesByCount    = true
    showSidebarCategories = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""
    
  # Sets Social Share links to appear on posts
  socialShare          = true
  # Sets specific share to appear on posts (default behavior is to appear)
  socialShareTwitter   = true
  socialShareGoogleplus = false
  socialShareFacebook  = true
  socialShareReddit    = true
  socialShareLinkedin  = true
  socialShareStumbleupon = false
  socialSharePinterest = false
  socialShareEmail     = true
    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]
    customCSS            = ["default"]
    customJS             = ["default"]
    #additionalCss = ["css/additional.css"]

    # Loading min files
    #customCSS            = ["/css/main.min.css"]
    #customJS             = ["/js/main.min.js"]


# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Marcin Biegała"

    paragraph = "Dev, motocyklista, marzyciel i miłośnik kawy."

    about     = ""

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/marcin_biegala_small.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = true
    width     = ""
    alt       = "Marcin Biegała"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 5

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 1

[[menu.main]]
    name = "Kategorie"
    url = "/categories"
    weight = 2

[[menu.main]]
    name = "O mnie"
    url = "/about"
    weight = 3

[[menu.main]]
    name = "Wystąpienia"
    url = "/speaking"
    weight = 4

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "biegal"
    stackoverflow    = "" # User Number
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "marcinbiegala"
    linkedin_company = ""
    slideshare      = ""
    #stackoverflow   = "1340855"
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "biegal"
    email           = "marcin@biegala.net"

